### ISSUE TITLE
Help,Is the right way to get the torrent file form infohash ?

### ISSUE THREAD

**Issue by LuYuChengProject** [the8472/mldht#11]
I ask a question on stackover , and  i follow you comment  . I'm a Java rookie , I try my best to understand you code .  Please give me little help , the following code is correct ? Thank you .

`
   byte[] infoHash = {16, (byte) 190, (byte) 236, 84, 103, (byte) 129, (byte) 209, (byte) 161, (byte) 153, (byte)      148, (byte) 214, (byte) 188, 94, (byte) 200, 127, 70, (byte) 152, (byte) 193, 31, (byte) 128};
       
 InetSocketAddress address = new InetSocketAddress("83.69.244.187", 63094);
       
 PullMetaDataConnection metaDataConnection = new PullMetaDataConnection(infoHash, address);
       
 metaDataConnection.canReadEvent();
      
ByteBuffer buffer = metaDataConnection.getMetaData().merge();
        
System.out.println(new String(buffer.array()));`

**Comment by the8472** [comment]
That particular class is not really *designed* to be run in a stand-alone fashion, but with some extra initialization it *might* work anyway.

Take a look at the initialization (the only class using `PullMetaDataConnection`) in [TorrentFetcher](https://github.com/the8472/mldht/blob/f1859ab5517c2ff59355d8659cc269fc02337e62/src/the8472/mldht/TorrentFetcher.java#L532-L604). The most important ones would be listener to get notified about completion and a `NIOConnectionManager` to get async network IO to work.

Alternatively you could look at [atomashpolskiy/bt](https://github.com/atomashpolskiy/bt), which might provide cleaner APIs.

**Comment by LuYuChengProject** [comment]
thanks :) 👍
