### ISSUE TITLE
publish to maven central

### ISSUE THREAD

**Issue by kg6zvp** [the8472/mldht#15]
Many folks use Maven or gradle for dependency resolution and not having this library available through maven is a barrier to adoption in this DevOPs-centered world.

**Comment by the8472** [comment]
The maven central registration workflow seems onerous and involves some *waiting for humans to judge your registration*. Since I don't need the library as maven dependency myself I'm not quite motivated to go through that.

How about other maven repos? [jitpack](https://jitpack.io/)? jcentral?

**Comment by kg6zvp** [comment]
Maven Central is always preferable, but I wouldn't mind configuring another repo like jitpack or jcentral if you're willing to publish your library on there.

If you'd like help submitting either to Maven Central or another repo, let me know.

Thanks for your consideration.

**Comment by the8472** [comment]
linked repos in the readme, see if things work for you. you can use the jitpack one to depend on current master.

**Comment by kg6zvp** [comment]
Thanks! Like I said, I don't mind helping out if you need it.
