### ISSUE TITLE
recognize seed/peer

### ISSUE THREAD

**Issue by XJIOP** [the8472/mldht#19]
cli getpeers always return seed:false
how to know is seed or peer? need info for uploaders/downloaders

**Comment by the8472** [comment]
The output was a bit misleading since the protocol has no way to determine whether an individual `get peers` response value is a seed or a peer. 

Try c4eeacd83819fc2a4e544405ec10e56eb11b103b, I added an option to the CLI to print actual scrape results

```
$ mldht-remote-cli getpeers -scrape 057107EBA2FC03DF1F231DE039C501E6585546AD

Scrape Result for 057107EBA2FC03DF1F231DE039C501E6585546AD: seeds[scrape]:263 peers[scrape]:425 direct results:77 ; 15/25 of nodes returning values supported scrape
```

**Comment by XJIOP** [comment]
That's what I need, thanks!

Another question, mldht-remote-cli has support mulltiple instance with different info_hash at same time?

**Comment by the8472** [comment]
you could just have tried it, but yes. You can also pass multiple infohashes in a single command, the help says as much.
