### ISSUE TITLE
getPeersDB.log empty

### ISSUE THREAD

**Issue by Bl4d3rR** [the8472/mldht#34]
Hello, 
Firstly, thanks for the nice work.
The Server is running, but my getPeersDB.log keeps being empty and I don't know what the Problem is. 
Do you know what could go wrong, that there is no logging?

The server is making GET_PEERS request, as shown in diagnostics.logs

![Screenshot from 2022-05-06 15-42-10](https://user-images.githubusercontent.com/101339132/167144843-bfa0d345-42b8-469a-8c09-669d79930f2f.png)

Thanks!

**Comment by the8472** [comment]
Did you add the `TorrentDumper` to the configuration?

Based on the *remote RPC* numbers it looks like you might be behind some sort of firewall that's blocking unsolicited requests? For a P2P network you need an unfiltered port.
And the IPv6 DHT is still smaller than the IPv4 one (even though libtorrent added support a while ago), perhaps you should focus on the IPv4 stats instead.

**Comment by Bl4d3rR** [comment]
Hey, thanks for the answer. I changed the fw settings and setup a redis an now it works like a charm.

Thanks for the great work, have a nice day!
